# Generated by Django 6.0.1 on 2026-03-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_saving_goal_recurring_debt'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('taken', 'Olingan qarz'), ('given', 'Berilgan qarz')], default='taken', max_length=16)),
                ('counterparty', models.CharField(help_text='Kimdan qarz oldingiz yoki kimga berdingiz', max_length=120)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField(help_text='Qarz olingan/berilgan sana')),
                ('due_date', models.DateField(blank=True, help_text='Qaytarish muddati (ixtiyoriy)', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarz va qarzdorliklar',
                'ordering': ['is_closed', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_closed'], name='expenses_de_user_id_2d2a30_idx'), models.Index(fields=['user', 'kind', 'is_closed'], name='expenses_de_user_id_72d231_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('interval', models.CharField(choices=[('monthly', 'Oylik'), ('weekly', 'Haftalik'), ('yearly', 'Yillik')], default='monthly', max_length=16)),
                ('next_payment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qayta takrorlanuvchi chiqim',
                'verbose_name_plural': 'Qayta takrorlanuvchi chiqimlar',
                'ordering': ['next_payment_date', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='expenses_re_user_id_297091_idx'), models.Index(fields=['user', 'next_payment_date'], name='expenses_re_user_id_f71ada_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=0, help_text="Yig'moqchi bo'lgan jami summa (so'm)", max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=0, default=0, help_text="Hozircha jamg'arilgan summa (so'm)", max_digits=12)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Jamg'arma maqsadi",
                'verbose_name_plural': "Jamg'arma maqsadlari",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='expenses_sa_user_id_941481_idx')],
            },
        ),
    ]
