# Generated by Django 6.0.1 on 2026-03-27 10:05

from django.db import migrations, models


def seed_original_amount(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    for e in Expense.objects.all().only("id", "amount"):
        e.original_amount = e.amount
        e.save(update_fields=["original_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_saving_goal_recurring_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(db_index=True, default='UZS', max_length=8),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate_to_uzs',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(seed_original_amount, migrations.RunPython.noop),
    ]
