# Generated by Django 6.0.1 on 2026-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_currency_expense_fx_rate_to_uzs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('currency', models.CharField(db_index=True, max_length=8)),
                ('rate_to_uzs', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['-date', 'currency'],
                'indexes': [models.Index(fields=['date', 'currency'], name='expenses_ex_date_8f6ea3_idx')],
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
