# Generated by Django 6.0.1 on 2026-03-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_add_saving_goal_recurring_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('payment_link', models.URLField(help_text="To'lov sahifasi yoki bot deep-link (donat uchun).")),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Donat usuli',
                'verbose_name_plural': 'Donat usullari',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_supporter',
            field=models.BooleanField(default=False, help_text='Donat qilgan/supporter foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('note', models.CharField(blank=True, help_text='Admin uchun izoh (chek, tranzaksiya ID va hokazo).', max_length=255)),
                ('confirmed', models.BooleanField(default=False, help_text='Tasdiqlangan donat (supporter statusini beradi).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='accounts.donationmethod')),
            ],
            options={
                'verbose_name': 'Donat',
                'verbose_name_plural': 'Donatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('saving', "Jamg'arma oshirish"), ('debt', 'Qarzdan chiqish'), ('spending_control', 'Xarajatlarni nazorat qilish')], default='saving', max_length=32)),
                ('preferred_currency', models.CharField(default='UZS', help_text='Asosiy valyuta (masalan: UZS, USD)', max_length=8)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='preferred_by_users', to='categories.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moliyaviy profil',
                'verbose_name_plural': 'Moliyaviy profillar',
            },
        ),
    ]
