# Generated by Django 6.0.1 on 2026-03-11 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=0, help_text="Ushbu oy uchun turkum byudjeti (so'm)", max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turkum byudjeti',
                'verbose_name_plural': "Turkum bo'yicha byudjetlar",
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='categories__user_id_b6d217_idx'), models.Index(fields=['category', 'year', 'month'], name='categories__categor_35c726_idx')],
                'unique_together': {('user', 'category', 'year', 'month')},
            },
        ),
    ]
