# Generated by Django 6.0.1 on 2026-03-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kanal nomi (admin uchun).', max_length=120)),
                ('username', models.CharField(help_text='@kanal_username (masalan, @chiqimlar_kanal) yoki short name.', max_length=64)),
                ('channel_id', models.BigIntegerField(blank=True, help_text="Ixtiyoriy: aniq channel_id (agar ma'lum bo'lsa).", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text="True bo'lsa — ushbu kanalda bo'lmagan user ilovaga kira olmaydi.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Majburiy kanal',
                'verbose_name_plural': 'Majburiy kanallar',
                'ordering': ['-created_at'],
            },
        ),
    ]
