# Generated by Django 6.0.1 on 2026-03-31 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('segment', models.CharField(choices=[('new', 'Yangi user (0-3 kun)'), ('active', 'Faol non-donater'), ('inactive', 'Noactive non-donater')], db_index=True, max_length=16)),
                ('topic', models.CharField(db_index=True, default='general', max_length=24)),
                ('text', models.TextField()),
                ('cta_url', models.CharField(blank=True, help_text='Masalan: /expenses/settings/', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['segment', '-weight', 'key'],
            },
        ),
        migrations.CreateModel(
            name='UserCampaignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_opt_out', models.BooleanField(default=False)),
                ('weekly_window_start', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('weekly_send_count', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_topic', models.CharField(blank=True, max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign state',
                'verbose_name_plural': 'Campaign states',
            },
        ),
        migrations.CreateModel(
            name='CampaignDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Xatolik'), ('skipped', "Qoidaga tushib o'tkazib yuborildi")], db_index=True, max_length=16)),
                ('skip_reason', models.CharField(blank=True, max_length=64)),
                ('message_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='notifications.campaignmessagetemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'sent_at'], name='notificatio_user_id_aa5082_idx'), models.Index(fields=['status', 'sent_at'], name='notificatio_status_f20639_idx')],
            },
        ),
    ]
